import foodModel from '../models/foodModel.js';
import fs from 'fs';

// Add food item
const addFood = async (req, res) => {
  try {
    // Check if image is uploaded
    if (!req.file) {
      return res.status(400).json({ success: false, message: "Image file is required" });
    }

    const image_filename = req.file.filename; // Filename generated by multer

    // Create a new food item
    const food = new foodModel({
      name: req.body.name,
      description: req.body.description,
      price: req.body.price,
      category: req.body.category,
      image: image_filename,
    });

    // Save the food item to the database
    await food.save();

    res.json({ success: true, message: "Food item added successfully" });
  } catch (error) {
    console.log(error);
    res.status(500).json({ success: false, message: "Failed to add food item" });
  }
};

// List all food items
const listFood = async (req, res) => {
  try {
    const foods = await foodModel.find({}); // Get all food items from the DB
    res.json({ success: true, data: foods });
  } catch (error) {
    console.log(error);
    res.status(500).json({ success: false, message: "Error fetching food items" });
  }
};

// Remove food item
const removeFood = async (req, res) => {
  try {
    // Find food item by ID
    const food = await foodModel.findById(req.body.id);
    if (!food) {
      return res.status(404).json({ success: false, message: "Food item not found" });
    }

    // Delete the image file from the file system
    fs.unlink(`uploads/${food.image}`, (err) => {
      if (err) {
        console.log("Error deleting file: ", err);
      }
    });

    // Delete the food item from the database
    await foodModel.findByIdAndDelete(req.body.id);

    res.json({ success: true, message: "Food item removed successfully" });
  } catch (error) {
    console.log(error);
    res.status(500).json({ success: false, message: "Error removing food item" });
  }
}

export { addFood, listFood, removeFood };
